# Generated by Django 4.1.3 on 2022-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_links_name_alter_links_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='registry/documents/category/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='NestedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting/documents/article/nested/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Вложенный документ',
                'verbose_name_plural': 'Вложенные документы',
            },
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_documents',
            field=models.ManyToManyField(blank=True, to='registry.categorydocuments', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='links',
            name='nested_documents',
            field=models.ManyToManyField(blank=True, to='registry.nesteddocuments', verbose_name='Вложенные документы'),
        ),
    ]
