# Generated by Django 4.1.3 on 2022-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting/documents/category/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='NestedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting/documents/article/nested/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Вложенный документ',
                'verbose_name_plural': 'Вложенные документы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='FreeZoneArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('nested_documents', models.ManyToManyField(blank=True, to='free_zone.nesteddocuments', verbose_name='Вложенные документы')),
                ('tags', models.ManyToManyField(blank=True, to='free_zone.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('article', models.ManyToManyField(blank=True, to='free_zone.freezonearticles', verbose_name='Статьи')),
                ('category_documents', models.ManyToManyField(blank=True, to='free_zone.categorydocuments', verbose_name='Документы')),
            ],
            options={
                'verbose_name': '1)Категория',
                'verbose_name_plural': '1)Категории',
            },
        ),
    ]
