# Generated by Django 4.1.3 on 2022-12-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting/documents/category/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_name', models.CharField(max_length=100, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='FormRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, verbose_name='Форма реализации')),
            ],
            options={
                'verbose_name': 'Форма реализации',
                'verbose_name_plural': 'Формы реализации',
            },
        ),
        migrations.CreateModel(
            name='NestedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting/documents/article/nested/', verbose_name='Документы по теме')),
            ],
            options={
                'verbose_name': 'Вложенный документ',
                'verbose_name_plural': 'Вложенные документы',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name1', models.CharField(max_length=100, verbose_name='Подкатегории 1')),
            ],
            options={
                'verbose_name': 'Подкатегория 1',
                'verbose_name_plural': 'Подкатегории 1',
            },
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name2', models.CharField(max_length=100, verbose_name='Подкатегория 2')),
            ],
            options={
                'verbose_name': 'Подкатегория 2',
                'verbose_name_plural': 'Подкатегории 2',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='OnpfArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onpf.executor', verbose_name='Исполнитель')),
                ('form_realization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onpf.formrealization', verbose_name='Форма реализации')),
                ('nested_documents', models.ManyToManyField(blank=True, to='onpf.nesteddocuments', verbose_name='Вложенные документы')),
                ('tags', models.ManyToManyField(blank=True, to='onpf.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('article', models.ManyToManyField(blank=True, to='onpf.onpfarticles', verbose_name='Статьи')),
                ('category_documents', models.ManyToManyField(blank=True, to='onpf.categorydocuments', verbose_name='Документы')),
                ('subcategory1', models.ManyToManyField(blank=True, to='onpf.subcategory', verbose_name='Подкатегории 1')),
                ('subcategory2', models.ManyToManyField(blank=True, to='onpf.subcategory2', verbose_name='Подкатегории 2')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
