# Generated by Django 4.1.3 on 2022-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onpf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory2',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory1',
            field=models.ManyToManyField(blank=True, to='onpf.category', verbose_name='Выбор категории 1-уровня'),
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='article',
            field=models.ManyToManyField(blank=True, to='onpf.onpfarticles', verbose_name='Статьи'),
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='subcategory2',
            field=models.ManyToManyField(blank=True, to='onpf.subcategory', verbose_name='Выбор категории 2-уровня'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name1',
            field=models.CharField(max_length=100, verbose_name='Название Подкатегории 2'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='subcategory_name2',
            field=models.CharField(max_length=100, verbose_name='Название Подкатегория 3'),
        ),
    ]
