# Generated by Django 4.1.3 on 2022-12-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onpf', '0002_remove_category_article_remove_category_subcategory1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydocuments',
            options={'verbose_name': 'Документ Категории', 'verbose_name_plural': 'Документы Категории'},
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='article',
        ),
        migrations.AddField(
            model_name='onpfarticles',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onpf.subcategory2', verbose_name='Категория'),
        ),
    ]
