# Generated by Django 4.1.3 on 2022-12-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
                ('npa', models.CharField(max_length=100, verbose_name='НПА')),
                ('deadline', models.DateTimeField(verbose_name='Срок')),
                ('deadline2', models.DateTimeField(verbose_name='Срок2')),
                ('supplies', models.CharField(max_length=100, verbose_name='Поставки')),
            ],
        ),
        migrations.CreateModel(
            name='TnVd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='SingleCustoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_rate', models.IntegerField(verbose_name='Ставка ввозной таможенной пошлины')),
                ('ETT', models.CharField(max_length=100, verbose_name='Ед. таможенной тарификации')),
                ('income', models.CharField(max_length=100, verbose_name='Доходы')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_vd.tnvd', verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.CharField(max_length=100, verbose_name='Запреты')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_vd.tnvd', verbose_name='Код')),
            ],
        ),
    ]
