# Generated by Django 4.1.3 on 2022-12-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_remove_category_article_tariffarticles_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
